# ==========Linear Regression(Evaluation Metrics)============

# 1. Import Necessary Libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# 2. Data Collection(Import Data)

In [3]:
cars_data2 = pd.read_csv("Cars.csv")
cars_data2

,HP,MPG,VOL,SP,WT
0,49,53.700681,89,104.185353,28.762059
1,55,50.013401,92,105.461264,30.466833
2,55,50.013401,92,105.461264,30.193597
3,70,45.696322,92,113.461264,30.632114
4,53,50.504232,92,104.461264,29.889149
...,...,...,...,...,...
76,322,36.900000,50,169.598513,16.132947
77,238,19.197888,115,150.576579,37.923113
78,263,34.000000,50,151.598513,15.769625
79,295,19.833733,119,167.944460,39.423099


# 3. Data Understanding

# 4. Data Preparation

## 4.1 Data Cleaning

## 4.2 Separate Inputs and Outputs

In [4]:
X = cars_data2[["HP","VOL","SP","WT"]]
X

,HP,VOL,SP,WT
0,49,89,104.185353,28.762059
1,55,92,105.461264,30.466833
2,55,92,105.461264,30.193597
3,70,92,113.461264,30.632114
4,53,92,104.461264,29.889149
...,...,...,...,...
76,322,50,169.598513,16.132947
77,238,115,150.576579,37.923113
78,263,50,151.598513,15.769625
79,295,119,167.944460,39.423099


In [5]:
y = cars_data2["MPG"]
y

0     53.700681
1     50.013401
2     50.013401
3     45.696322
4     50.504232
        ...    
76    36.900000
77    19.197888
78    34.000000
79    19.833733
80    12.101263
Name: MPG, Length: 81, dtype: float64

# 5. Model Building

In [6]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size= 0.80, random_state= 34, shuffle= True)
X_train, X_test, y_train, y_test

(     HP  VOL          SP         WT
 17   92   50  117.598513  16.194122
 52  115  124  120.404312  40.398164
 16   78   91  114.369293  29.535784
 39  130   92  128.461264  30.115434
 22   95  101  120.288996  32.675828
 ..  ...  ...         ...        ...
 11   92   50  117.598513  15.753535
 69  245  112  158.300669  37.141733
 35   90   98  115.013085  31.911223
 68  165  123  133.312342  40.472042
 33  102  113  121.392639  37.573290
 
 [64 rows x 4 columns],
      HP  VOL          SP         WT
 59  100  115  115.576579  37.662874
 49  115  101  118.288996  33.458472
 7    62   50  102.598513  15.847758
 27   92   99  119.105055  32.835069
 74  140  129  121.864163  42.618698
 61  120  116  117.668550  37.860411
 64  150  121  128.128401  40.159482
 12   92   99  122.105055  32.813592
 44   93  102  114.380966  33.078632
 30   84  114  113.484609  37.042350
 0    49   89  104.185353  28.762059
 15   73   89  111.185353  29.604527
 3    70   92  113.461264  30.632114
 48  130   8

In [10]:
X_train

,HP,VOL,SP,WT
17,92,50,117.598513,16.194122
52,115,124,120.404312,40.398164
16,78,91,114.369293,29.535784
39,130,92,128.461264,30.115434
22,95,101,120.288996,32.675828
...,...,...,...,...
11,92,50,117.598513,15.753535
69,245,112,158.300669,37.141733
35,90,98,115.013085,31.911223
68,165,123,133.312342,40.472042


In [11]:
linear_model = LinearRegression()

# 6. Model Training

In [12]:
linear_model.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [13]:
linear_model.intercept_

np.float64(30.210465141017654)

In [14]:
linear_model.coef_

array([-0.19986292, -0.4641794 ,  0.37782621,  0.84652445])

# 7. Model Testing

## 7.1 Training Data

In [15]:
y_pred_train = linear_model.predict(X_train)
y_pred_train

array([46.75462614, 29.357921  , 40.59531094, 35.55326361, 37.45059013,
       41.68332337, 32.74736225, 38.35204467, 15.7960024 , 40.45702296,
       39.41888236, 37.47703884, 41.42599626, 23.56427857, 41.17403166,
       26.5237502 , 28.78854008, 35.36168615, 34.25957557, 45.49336752,
       28.4717663 , 35.06820535, 37.09928504, 35.15766796, 36.67235696,
       33.15321636, 42.01639762, 27.80720182, 39.307307  , 38.31289001,
       35.40477942, 23.98357674, 20.38133197, 35.57491245, 36.87008928,
       37.67749978, 41.91914635, 38.82344891, 41.18680984, 30.1294102 ,
       26.62411662, 12.83999048, 36.13102051, 37.3420992 , 35.52563974,
       47.2231036 , 34.40109066, 26.95474873, 37.18263291, 37.54744214,
       33.34178579, 22.83470605, 42.72264178, 25.77796412, 38.23393319,
       19.94553155, 21.76768197, 40.92851149, 36.08544444, 46.38165859,
       20.50748319, 37.20180937, 24.76848656, 35.04420344])

## 7.2 Test Data

In [16]:
y_pred_test = linear_model.predict(X_test)
y_pred_test

array([32.39394585, 33.36020646, 46.7899155 , 38.66601593, 24.47175816,
       28.8901298 , 26.47157047, 39.78131375, 35.4949115 , 34.74024237,
       42.81695793, 41.37820079, 42.31502785, 36.39884247, 25.06481155,
       18.25707928, 42.15044765])

# 8. Model Evaluation

## 8.1 Training Data Evaluation Metrics

In [18]:
error = y_train -  y_pred_train
error

17   -7.400532
52    0.272015
16    2.194598
39   -4.539133
22    0.860016
        ...   
11   -7.027564
69    0.766225
35    0.756934
68   -1.665315
33    1.241253
Name: MPG, Length: 64, dtype: float64

In [19]:
error.mean()

np.float64(-7.827072323607354e-15)

In [20]:
#(OR)

In [21]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [22]:
mean_absolute_error(y_true = y_train,y_pred = y_pred_train)    # MAE   #Same Units

3.129830577722012

In [23]:
# MAE,predicted result la irundhu avg ah 3.12 maarum

In [24]:
mean_squared_error(y_true = y_train, y_pred = y_pred_train)    # MSE   #Squared output Units

17.7676167791103

In [25]:
# MSE,predicted result la irundhu avg ah 17.76 maarum

In [26]:
root_mean_squared_error(y_true = y_train,y_pred = y_pred_train)  #Normalize the Units

4.215165095119087

In [27]:
r2_score(y_true = y_train,y_pred = y_pred_train)     # How much datas will contribute for the output

0.7657768244482416

In [28]:
# 76% of data will contribute

In [29]:
import statsmodels.formula.api as smf

In [30]:
cars_data2.head()

,HP,MPG,VOL,SP,WT
0,49,53.700681,89,104.185353,28.762059
1,55,50.013401,92,105.461264,30.466833
2,55,50.013401,92,105.461264,30.193597
3,70,45.696322,92,113.461264,30.632114
4,53,50.504232,92,104.461264,29.889149


### To see Adjusted R2 score, we are using OLS Technique from StatsModels Formula

In [31]:
linear_stats_model = smf.ols(formula = "MPG ~ HP+VOL+SP+WT", data = cars_data2).fit()
linear_stats_model

In [32]:
print("R2 Score: ",linear_stats_model.rsquared.round(4),"\nAdjusted R2 Score: ",linear_stats_model.rsquared_adj.round(4))  # \n - moveon to below line

R2 Score:  0.7705 
Adjusted R2 Score:  0.7585


In [ ]:
#R2 will be increasing when you add more features...see the below to understand this

In [33]:
# only 1 input feature
linear_stats_model = smf.ols(formula = "MPG ~ HP", data = cars_data2).fit()

In [34]:
print("R2 Score: ",linear_stats_model.rsquared.round(4),"\nAdjusted R2 Score: ",linear_stats_model.rsquared_adj.round(4))

R2 Score:  0.5257 
Adjusted R2 Score:  0.5197


In [35]:
# 2 input feature
linear_stats_model = smf.ols(formula = "MPG ~ HP+VOL", data = cars_data2).fit()

In [36]:
print("R2 Score: ",linear_stats_model.rsquared.round(4),"\nAdjusted R2 Score: ",linear_stats_model.rsquared_adj.round(4))

R2 Score:  0.7507 
Adjusted R2 Score:  0.7443


In [38]:
# 3 input feature
linear_stats_model = smf.ols(formula = "MPG ~ HP+VOL+SP", data = cars_data2).fit()

In [39]:
print("R2 Score: ",linear_stats_model.rsquared.round(4),"\nAdjusted R2 Score: ",linear_stats_model.rsquared_adj.round(4))

R2 Score:  0.7704 
Adjusted R2 Score:  0.7614


In [41]:
# 4 input feature
linear_stats_model = smf.ols(formula = "MPG ~ HP+VOL+SP+WT", data = cars_data2).fit()

In [42]:
print("R2 Score: ",linear_stats_model.rsquared.round(4),"\nAdjusted R2 Score: ",linear_stats_model.rsquared_adj.round(4))

R2 Score:  0.7705 
Adjusted R2 Score:  0.7585


##### Conclusion:
  - **R2 score** will ***keep increasing*** no matter how many inputs you increase and whether the added inputs contibuting more to the predictions or not.
  - But **Adjusted R2 score** will ***Not keep increasing*** if you keep increasing the inputs
    (**Adjusted R2 score** will only increase only if the added new input features is contributing more for the prediction).
  - Adding more Inputs will reduce the Error, so if  **Inputs** increases = **Residual** decreases...if **Inputs** increases = **R2** increases 

## 8.2 Test Data Evaluation Metrics

In [44]:
mean_absolute_error(y_true = y_test, y_pred = y_pred_test)

3.885609698062919

In [45]:
mean_squared_error(y_true = y_test, y_pred = y_pred_test)

24.4931887283102

In [46]:
root_mean_squared_error(y_true = y_test, y_pred = y_pred_test)

4.949059378135425

In [47]:
r2_score(y_true = y_test, y_pred = y_pred_test)

0.7674401633557068